site_name: Pyspark MSGraph Source
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/"]  # or wherever your package code is
          options:
            show_source: true

nav:
  - Home: index.md
  - API Reference:
      - Overview: api/index.md
      - Core: api/core.md
