name: Publish to Test PyPI

on:
  push:
  workflow_dispatch:
    inputs:
      publish_to_testpypi:
        description: "Publish to Test PyPI?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Show extracted version
        run: echo "Publishing version $VERSION"

      - name: Build the package
        run: poetry build

      - name: Publish to Test PyPI
        if: ${{ github.event.inputs.publish_to_testpypi == 'true' }}
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi --build
